/**
 * Password hashing and session cookies.
 *
 * Each account holds a CV and a private job pipeline, so every route is closed by default and
 * opened only by an explicit check. Passwords are PBKDF2-SHA256 with a per-user salt; sessions are
 * HMAC-signed cookies carrying the owner id, so a tampered cookie cannot select another account.
 */

const SESSION_COOKIE = 'ike_session';
const SESSION_TTL_MS = 14 * 24 * 60 * 60 * 1000;
const PBKDF2_ITERATIONS = 210_000;

const encoder = new TextEncoder();

function toBase64(bytes: ArrayBuffer | Uint8Array) {
  const view = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  let binary = '';
  for (const byte of view) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function fromBase64(value: string) {
  const binary = atob(value);
  return Uint8Array.from(binary, (character) => character.charCodeAt(0));
}

/** Compares in constant time so a wrong password cannot be found one character at a time. */
function timingSafeEqual(a: Uint8Array, b: Uint8Array) {
  if (a.length !== b.length) return false;
  let difference = 0;
  for (let index = 0; index < a.length; index += 1) difference |= a[index] ^ b[index];
  return difference === 0;
}

async function pbkdf2(password: string, salt: Uint8Array, iterations: number) {
  const saltBuffer = new Uint8Array(salt).buffer;
  const key = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: saltBuffer, iterations, hash: 'SHA-256' }, key, 256);
  return new Uint8Array(bits);
}

/** Format: pbkdf2$<iterations>$<saltBase64>$<hashBase64>. Generated by `npm run set-password`. */
export async function hashPassword(password: string, iterations = PBKDF2_ITERATIONS) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const hash = await pbkdf2(password, salt, iterations);
  return `pbkdf2$${iterations}$${toBase64(salt)}$${toBase64(hash)}`;
}

export async function verifyPassword(password: string, stored: string) {
  const parts = stored.split('$');
  if (parts.length !== 4 || parts[0] !== 'pbkdf2') return false;
  const iterations = Number(parts[1]);
  if (!Number.isFinite(iterations) || iterations < 1000) return false;
  try {
    const candidate = await pbkdf2(password, fromBase64(parts[2]), iterations);
    return timingSafeEqual(candidate, fromBase64(parts[3]));
  } catch {
    return false;
  }
}

async function sign(value: string, secret: string) {
  const key = await crypto.subtle.importKey('raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  return toBase64(await crypto.subtle.sign('HMAC', key, encoder.encode(value)));
}

/** The signed payload carries the owner, so a tampered cookie cannot select another user's data. */
export async function createSessionValue(userId: string, secret: string, now = Date.now()) {
  const payload = `${userId}:${now + SESSION_TTL_MS}`;
  return `${payload}.${await sign(payload, secret)}`;
}

export async function readSessionValue(value: string, secret: string, now = Date.now()): Promise<string> {
  const separator = value.lastIndexOf('.');
  if (separator < 1) return '';
  const payload = value.slice(0, separator);
  const signature = value.slice(separator + 1);
  const [userId, expiry] = payload.split(':');
  if (!userId || !/^\d+$/.test(expiry ?? '') || Number(expiry) < now) return '';
  try {
    // Verify before trusting any part of the payload.
    if (!timingSafeEqual(fromBase64(signature), fromBase64(await sign(payload, secret)))) return '';
    return userId;
  } catch {
    return '';
  }
}

export function readCookie(request: Request, name = SESSION_COOKIE) {
  const header = request.headers.get('cookie') ?? '';
  for (const part of header.split(';')) {
    const [key, ...rest] = part.trim().split('=');
    if (key === name) return rest.join('=');
  }
  return '';
}

export function sessionCookie(value: string, secure: boolean, maxAgeSeconds = SESSION_TTL_MS / 1000) {
  // HttpOnly keeps the token away from scripts; SameSite=Strict is what stops cross-site requests
  // riding the session, which is this app's CSRF defence.
  return [
    `${SESSION_COOKIE}=${value}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Strict',
    secure ? 'Secure' : '',
    `Max-Age=${Math.floor(maxAgeSeconds)}`,
  ].filter(Boolean).join('; ');
}

export function clearedSessionCookie(secure: boolean) {
  return sessionCookie('', secure, 0);
}

/**
 * Rejects cross-origin state changes. SameSite=Strict already blocks the browser from sending the
 * cookie, and this second check covers clients that do not enforce it.
 */
export function isSameOrigin(request: Request) {
  const origin = request.headers.get('origin');
  if (!origin) return true;
  try {
    return new URL(origin).host === new URL(request.url).host;
  } catch {
    return false;
  }
}
