/**
 * Password hashing and session cookies.
 *
 * Each account holds a private job pipeline, so every route is closed by default and
 * opened only by an explicit check. Passwords are PBKDF2-SHA256 with a per-user salt; sessions are
 * HMAC-signed cookies carrying the owner id, so a tampered cookie cannot select another account.
 */
const SESSION_COOKIE = 'ike_session';
const SESSION_TTL_MS = 14 * 24 * 60 * 60 * 1000;
/**
 * Password-hashing policy (T34).
 *
 * The iteration count is the version: `parsePasswordHash()` reads it back out of every
 * stored hash, `passwordHashNeedsRehash()` compares it against the current target, and a
 * successful login upgrades a legacy hash without ever needing the old password in
 * plaintext beyond the verification that just succeeded.
 *
 * - Cloudflare Workers rejects PBKDF2 above 100,000 iterations, so the hosted Worker
 *   keeps creating and verifying 100,000-iteration hashes.
 * - Node (local dev/test and the VPS target) has no such cap and uses 600,000, the
 *   OWASP 2023 minimum for PBKDF2-HMAC-SHA256. Benchmarked locally at ~145 ms per
 *   hash with `npm run benchmark:password-hash`; re-run that script on the VPS before
 *   treating the number as reviewed there, and tune with `PASSWORD_HASH_ITERATIONS`.
 * - Verification accepts any iteration count in range, so each runtime verifies the
 *   other's hashes (up to the Workers cap) and Node upgrades legacy hashes on login.
 */
export const PASSWORD_HASH_ALGORITHM = 'PBKDF2-SHA256';
export const WORKERS_PBKDF2_CAP = 100_000;
export const NODE_PBKDF2_ITERATIONS = 600_000;
export const PBKDF2_SALT_BYTES = 16;
export const PBKDF2_HASH_BYTES = 32;
/** Verification floor: below this a stored hash is rejected outright, never upgraded. */
export const MIN_PBKDF2_ITERATIONS = 1000;
/** Verification ceiling: a stored count above this is rejected to bound login work. */
export const MAX_PBKDF2_ITERATIONS = 2_000_000;

function isNodeRuntime() {
  return typeof process !== 'undefined' && Boolean((process as { versions?: { node?: string } }).versions?.node);
}

/** Iteration target for newly created hashes: env override, else per-runtime default. */
export function currentPasswordIterations() {
  const override = typeof process !== 'undefined'
    ? Number((process as { env?: Record<string, string | undefined> }).env?.PASSWORD_HASH_ITERATIONS)
    : NaN;
  if (Number.isInteger(override) && override >= MIN_PBKDF2_ITERATIONS && override <= MAX_PBKDF2_ITERATIONS) {
    return override;
  }
  return isNodeRuntime() ? NODE_PBKDF2_ITERATIONS : WORKERS_PBKDF2_CAP;
}

const encoder = new TextEncoder();

function toBase64(bytes: ArrayBuffer | Uint8Array) {
  const view = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  let binary = '';
  for (const byte of view) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function fromBase64(value: string) {
  const binary = atob(value);
  return Uint8Array.from(binary, (character) => character.charCodeAt(0));
}

/** Compares in constant time so a wrong password cannot be found one character at a time. */
function timingSafeEqual(a: Uint8Array, b: Uint8Array) {
  if (a.length !== b.length) return false;
  let difference = 0;
  for (let index = 0; index < a.length; index += 1) difference |= a[index] ^ b[index];
  return difference === 0;
}

async function pbkdf2(password: string, salt: Uint8Array, iterations: number) {
  const saltBuffer = new Uint8Array(salt).buffer;
  const key = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: saltBuffer, iterations, hash: 'SHA-256' }, key, 256);
  return new Uint8Array(bits);
}

/** Format: pbkdf2$<iterations>$<saltBase64>$<hashBase64>. Generated by `npm run set-password`. */
export async function hashPassword(password: string, iterations = currentPasswordIterations()) {
  const salt = crypto.getRandomValues(new Uint8Array(PBKDF2_SALT_BYTES));
  const hash = await pbkdf2(password, salt, iterations);
  return `pbkdf2$${iterations}$${toBase64(salt)}$${toBase64(hash)}`;
}

export interface ParsedPasswordHash {
  iterations: number;
  salt: Uint8Array;
  hash: Uint8Array;
}

/** Reads the version (iteration count) back out of a stored hash; null means malformed. */
export function parsePasswordHash(stored: string): ParsedPasswordHash | null {
  const parts = stored.split('$');
  if (parts.length !== 4 || parts[0] !== 'pbkdf2') return null;
  const iterations = Number(parts[1]);
  if (!Number.isInteger(iterations) || iterations < MIN_PBKDF2_ITERATIONS || iterations > MAX_PBKDF2_ITERATIONS) {
    return null;
  }
  try {
    const salt = fromBase64(parts[2]);
    const hash = fromBase64(parts[3]);
    if (salt.length !== PBKDF2_SALT_BYTES || hash.length !== PBKDF2_HASH_BYTES) return null;
    return { iterations, salt, hash };
  } catch {
    return null;
  }
}

/**
 * True when a stored hash verifies but was created under an older policy and should be
 * upgraded on the next successful login. Never true for a hash stronger than the
 * current target: verification must not downgrade.
 */
export function passwordHashNeedsRehash(stored: string, target = currentPasswordIterations()) {
  const parsed = parsePasswordHash(stored);
  if (!parsed) return false;
  return parsed.iterations < target;
}

export async function verifyPassword(password: string, stored: string) {
  const parsed = parsePasswordHash(stored);
  if (!parsed) return false;
  try {
    const candidate = await pbkdf2(password, parsed.salt, parsed.iterations);
    return timingSafeEqual(candidate, parsed.hash);
  } catch {
    return false;
  }
}

async function sign(value: string, secret: string) {
  const key = await crypto.subtle.importKey('raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  return toBase64(await crypto.subtle.sign('HMAC', key, encoder.encode(value)));
}

/**
 * The signed payload carries the owner and their session epoch, so a tampered cookie cannot select
 * another user's data and raising the epoch invalidates every cookie already issued to them.
 */
export async function createSessionValue(userId: string, secret: string, epoch = 1, now = Date.now()) {
  const payload = `${userId}:${epoch}:${now + SESSION_TTL_MS}`;
  return `${payload}.${await sign(payload, secret)}`;
}

export interface SessionClaims {
  userId: string;
  epoch: number;
}

export async function readSessionValue(value: string, secret: string, now = Date.now()): Promise<SessionClaims | null> {
  const separator = value.lastIndexOf('.');
  if (separator < 1) return null;
  const payload = value.slice(0, separator);
  const signature = value.slice(separator + 1);
  const [userId, epoch, expiry] = payload.split(':');
  if (!userId || !/^\d+$/.test(epoch ?? '') || !/^\d+$/.test(expiry ?? '') || Number(expiry) < now) return null;
  try {
    // Verify before trusting any part of the payload.
    if (!timingSafeEqual(fromBase64(signature), fromBase64(await sign(payload, secret)))) return null;
    return { userId, epoch: Number(epoch) };
  } catch {
    return null;
  }
}

export function readCookie(request: Request, name = SESSION_COOKIE) {
  const header = request.headers.get('cookie') ?? '';
  for (const part of header.split(';')) {
    const [key, ...rest] = part.trim().split('=');
    if (key === name) return rest.join('=');
  }
  return '';
}

export function sessionCookie(value: string, secure: boolean, maxAgeSeconds = SESSION_TTL_MS / 1000) {
  // HttpOnly keeps the token away from scripts; SameSite=Strict is what stops cross-site requests
  // riding the session, which is this app's CSRF defence.
  return [
    `${SESSION_COOKIE}=${value}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Strict',
    secure ? 'Secure' : '',
    `Max-Age=${Math.floor(maxAgeSeconds)}`,
  ].filter(Boolean).join('; ');
}

export function clearedSessionCookie(secure: boolean) {
  return sessionCookie('', secure, 0);
}

/**
 * Rejects cross-origin state changes. An origin includes the scheme and port, not just the host:
 * http://example.test and https://example.test are different browser origins. SameSite=Strict
 * already blocks most cross-site cookie use; this check also covers clients that do not enforce it.
 */
export function isSameOrigin(request: Request) {
  const origin = request.headers.get('origin');
  if (!origin) return true;
  try {
    return new URL(origin).origin === new URL(request.url).origin;
  } catch {
    return false;
  }
}

/** First-account self-registration is only an installer convenience for the local environments. */
export function isLocalBootstrapRequest(request: Request) {
  const url = new URL(request.url);
  return ['localhost', '127.0.0.1', '[::1]'].includes(url.hostname);
}
